### ISSUE TITLE
Section - Messaging Architecture

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Demographic-Event-Messages#4]
The section around messaging architecture should not be required in the DemographicUpdateBeta spec as the spec should say in the overview section that the events will be sent via the EMS, with a link to the spec. This section could probably be condensed down to a single page outlining the general structure but referring heavily back to the EMS spec for specifics of the Header and bundle requirements.

If these requirements are left in this spec there will be duplication which risks contradictions being introduced in later version of the specificaitons.

**Comment by bushra** [comment]
Agreed - this page will refer to the EMS specification.
