### ISSUE TITLE
Page - Example Messages

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Demographic-Event-Messages#5]
The page Example Messages (https://developer.nhs.uk/apis/demographicupdates-beta/explore_example_messages.html):

1. would probably be better being after the message specification pages on the left hand menu so that people know what messages are applicable to this specification.

2. As implied by point 1, the links link to a list of examples, some relvant to this spec and some relevant to other event message specs. It might be better to list the examples directly in JSON and XML with a description to explain the trigger for the event message.

3. Some of the exmple from the two different sources are different, such as birth notification message has different patient resources. It would be worth going through each example and checking that it is valid.

**Comment by bushra** [comment]
The specification will be updated to refer to XML only as JSON is not within the current scope of EMS. 
The examples have been produced at the time to meet technical validation and not to represent a use case as this information was not available. 

I think user interest in the specification lies highly with the Example Messages, so I've kept this at the top to answer the question as to their whereabouts earlier!
