### ISSUE TITLE
Page - PDS Change of Address

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Demographic-Event-Messages#6]
The PDS Change of Address page (https://developer.nhs.uk/apis/demographicupdates-beta/explore_pds_change_of_address.html) could benefit from some additional information and there are a couple of bugs.

1. This page could do with an introduction explaining when this message is going to be produced. A diagram showing the resources and how they are linked in the event message bundle would help the reader quickly visualize what to expect in the event.

2. The Data item requirements table is a bit difficult to read as there is the "PDS Change of Address data item name" column which has names which do not make clear what the elements are. It might be better to break it up into headers for each element so that there can be an address slice outlined for new address and an address slice for the previous address with the requirements around each address population. This would make it easier to explain how someone should consume the resource and recognise the previous address, is this the address end date or address use as the examples have the address use of "old" for the old address.

3. The Address Effective To Date in the table for the new address is mandatory which implies that the date is known when the patient is going to leave that address. This does not make sense and should probably be required. Address effective from date should probably be mandatory instead of required though.

4. There is PAF Key and address description which say not yet profiled. These should either be removed until introduced or explained in the spec as they will currently cause confusion.

5. This page would also benefit from an example of the JSON/XML.

6. There should be details around specific values which have to be set, which relate to the common envent message structure such as "EMS-EventType-1" (https://fhir.nhs.uk/STU3/CodeSystem/EMS-EventType-1) which has to be set in the event header resource. Also what the focus element should point towards in the bundle.

**Comment by bushra** [comment]
Points 2, 3, 4, 5, and 6 have been resolved via changes to the page or in issues where the same comment has been raised.

**Comment by james-answer** [comment]
These changes have been made and merged into the current version of the specificaion.
