### ISSUE TITLE
Page - PDS Change of GP

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Demographic-Event-Messages#7]
The PDS Change of GP page (https://developer.nhs.uk/apis/demographicupdates-beta/explore_pds_change_of_gp.html) it would be helpul to a reader if there was the following additional information.

1. This page could do with an introduction explaining when this message is going to be produced. A diagram showing the resources and how they are linked in the event message bundle would help the reader quickly visualize what to expect in the event. Especially which resource is the focus of the event.

2. This page would also benefit from an example of the JSON/XML.

3. There should be details around specific values which have to be set, which relate to the common envent message structure such as "EMS-EventType-1" (https://fhir.nhs.uk/STU3/CodeSystem/EMS-EventType-1) which has to be set in the event header resource.

4. The purpose of each resource should be exmplained as it is difficult to understand the purpose of the elements. For example it is only from the example that I worked out that there should be one Episode of care in the bundle referring to the old GP and the new GP seems to be included in the "generalPractitioner" element of the patient resource. This information should be included in the spec as it will make it simpler and less error prone for a consumer of the event to process the event correctly.

5. Not on this page but the related examples are incorrect as the references such as focus do not actually reference resources within the bundle.

6. What is the difference between the "Business Effective dates" and the "System Effective dates"?

**Comment by bushra** [comment]
2. XML examples are available on the FHIR reference server, reference to which has been made under the Example Messages page. This is to avoid maintaining examples in multiple places, and avoid long webpages.
3. This has been applied/
6. In PDS, business effective date will be the effective dates for the GP registration, and system effective dates will be the dates when those changes were recorded on the system.

**Comment by james-answer** [comment]
I have changes to the "PDS Change of GP" event message page to include life cycle, resource relationships and population guidance for the bundle.

I have pushed the changes to a feature branch "feature/death_event_life_cycle".

@bushra The changes I have made are based on the examples and origional wording, the meaning should be the same but could you have a quick look over it and check that the page reflects what you believe to have been built.

**Comment by james-answer** [comment]
Spec has been updated and merged into the latest version of the spec so closing this issue.
