### ISSUE TITLE
Page - PDS Person Death

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Demographic-Event-Messages#8]
The PDS Person Death page (https://developer.nhs.uk/apis/demographicupdates-beta/explore_pds_person_death.html) would be more useful for a person implementing a consumer of the event if it had the following detail.

1. This page could do with an introduction explaining when this message is going to be produced. A diagram showing the resources and how they are linked in the event message bundle would help the reader quickly visualize what to expect in the event.

2. There should be details around specific values which have to be set, which relate to the common envent message structure such as "EMS-EventType-1" (https://fhir.nhs.uk/STU3/CodeSystem/EMS-EventType-1) which has to be set in the event header resource.

3. The purpose of each resource should be exmplained in more detail along with the links between them. In the current examples there is no link to the DeathNotification Communication resource from any other resource, this should probably be the reference from the payload element rather than the patient. The patient is referenced as the ssubject from the death notification communicaiton resource so would be linked back to the MessageHeader resource.

4. This page would also benefit from an example of the JSON/XML being included on the page.

**Comment by bushra** [comment]
For option 2. I'll apply this to the event messages as it's an approach already applied elsewhere.

**Comment by james-answer** [comment]
I have made some proposed changes to this page around the event life cycle and additional population guidance for the resources. I have pushed the changes to a feature branch "feature/death_event_life_cycle".

**Comment by james-answer** [comment]
Page reviewed and merged into the current spec release so closing.
