### ISSUE TITLE
Section - Help & Support

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Demographic-Event-Messages#9]
The "Help & Support - About" page (https://developer.nhs.uk/apis/demographicupdates-beta/support_about.html) should probably just focus on help and support as the about is covered in the overview section. This page should really focus on contacts for issues, questions or enquiries. The Interopen and FHIR bits do not really add anything to the specificaion.

The "CareConnect FHIR Profiles" page (https://developer.nhs.uk/apis/demographicupdates-beta/support_careconnect.html) should be in the overview section of the spec if it is going to be included. It does not add anything to the spec so should probably just be removed. The profiles the event specification uses are actually DCH or EMS derived profiles so we are not actually using the CareConnect Organization and Patient resources.

**Comment by bushra** [comment]
Help & Support has been changed to About. 

The CareConnect FHIR Profiles page will remain to clarify which INTEROPen FHIR profiles have been constrained further for use by the Demographic Update events.
